# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBInstanceId', models.CharField(max_length=20, null=True)),
                ('DBInstanceName', models.CharField(max_length=20, null=True)),
                ('DBInstanceCreatetime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date published')),
                ('DBInstancestatus', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
