# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBInstanceId', models.CharField(max_length=20)),
                ('DBInstanceName', models.CharField(max_length=20)),
                ('DBInstanceCreatetime', models.DateTimeField(verbose_name='date published')),
                ('DBInstancestatus', models.CharField(max_length=10)),
            ],
        ),
    ]
