# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='DBInstanceCreatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 14, 32, 43, 494839), verbose_name='date published'),
        ),
    ]
