# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0004_auto_20161215_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='DBInstanceCreatetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 15, 14, 34, 33, 413245, tzinfo=utc), verbose_name='date published'),
        ),
    ]
