# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0005_auto_20161215_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='DBInstanceCreatetime',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
