# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0006_auto_20161215_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinstance',
            name='DBInstanceCreatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
