# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0007_auto_20161215_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinstance',
            name='DBInstanceCreatetime',
        ),
        migrations.RemoveField(
            model_name='dbinstance',
            name='DBInstanceName',
        ),
        migrations.RemoveField(
            model_name='dbinstance',
            name='DBInstancestatus',
        ),
    ]
