# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0008_auto_20161215_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbinstance',
            name='DBInstanceCreatetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='dbinstance',
            name='DBInstanceName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dbinstance',
            name='DBInstancestatus',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dbinstance',
            name='DBInstanceId',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
